// Generated by CoffeeScript 1.6.2
var americano, initProxy, port, request, setupRealtime;

americano = require('americano');

request = require('request-json');

initProxy = require('./server/initializers/proxy');

setupRealtime = require('./server/initializers/realtime');

process.on('uncaughtException', function(err) {
  console.error(err);
  return console.error(err.stack);
});

port = process.env.PORT || 9103;

americano.start({
  name: 'Cozy Home',
  port: port
}, function(app, server) {
  var ctrler;

  app.server = server;
  if (process.env.NODE_ENV !== "test") {
    initProxy();
  }
  ctrler = require('./server/controllers/applications').loadApplication;
  app.param('slug', ctrler);
  setupRealtime(app);
  if (typeof callback !== "undefined" && callback !== null) {
    return callback(app);
  }
});
