// Generated by CoffeeScript 1.6.2
var UserPreference, americano;

americano = require('americano-cozy');

module.exports = UserPreference = americano.getModel('UserPreference', {
  backgroundColor: String,
  buttonColor: String,
  buttonHoverColor: String
});

UserPreference.all = function(callback) {
  return UserPreference.request("all", callback);
};
