// Generated by CoffeeScript 1.6.2
var Adapter, client, request;

request = require("request-json");

client = request.newClient("http://localhost:9101/");

module.exports = Adapter = (function() {
  function Adapter() {}

  Adapter.prototype.updateKeys = function(pwd, callback) {
    var name, token,
      _this = this;

    if (process.env.NODE_ENV === "production" || process.env.NODE_ENV === "test") {
      name = process.env.NAME;
      token = process.env.TOKEN;
      client.setBasicAuth(name, token);
    }
    return client.put("accounts/password/", {
      password: pwd
    }, function(err, res, body) {
      return callback(err);
    });
  };

  Adapter.prototype.initializeKeys = function(pwd, callback) {
    var name, token,
      _this = this;

    if (process.env.NODE_ENV === "production" || process.env.NODE_ENV === "test") {
      name = process.env.NAME;
      token = process.env.TOKEN;
      client.setBasicAuth(name, token);
    }
    return client.post("accounts/password/", {
      password: pwd
    }, function(err, res, body) {
      return callback(err);
    });
  };

  return Adapter;

})();
