// Generated by CoffeeScript 1.6.2
var fs, https, url, util;

fs = require('fs');

https = require('https');

url = require('url');

util = require('util');

exports.DescriptionManager = (function() {
  function DescriptionManager() {
    this.description = " ";
  }

  DescriptionManager.prototype.get = function(app, callback) {
    var config, options, path, request,
      _this = this;

    path = app.git.substring(19, app.git.length - 4);
    path = "https://raw.github.com/" + path + '/master/package.json';
    options = {
      host: url.parse(path).host,
      path: url.parse(path).path
    };
    config = "";
    request = https.get(options, function(response) {
      if (response.headers.status !== "404 Not Found") {
        return response.on('data', function(data) {
          return config = JSON.parse(data);
        }).on('end', function() {
          _this.metaData = {};
          if (config.description != null) {
            _this.metaData.description = config.description;
          }
          if (config.name != null) {
            _this.metaData.name = config.name.replace('cozy-', '');
          }
          if (config['cozy-displayName'] != null) {
            _this.metaData.displayName = config['cozy-displayName'];
          } else {
            _this.metaData.displayName = config.name.replace('cozy-', '');
          }
          if (config['cozy-permissions'] != null) {
            _this.metaData.permissions = config['cozy-permissions'];
          }
          return callback(_this.metaData);
        });
      } else {
        return callback({
          code: 404,
          msgs: ['package.json not found']
        }, null);
      }
    });
    return request.on('error', function(error) {
      return callback(null, " ");
    });
  };

  return DescriptionManager;

})();
