// Generated by CoffeeScript 1.6.2
(function() {
  var fs, request, url;

  fs = require('fs');

  url = require('url');

  request = require('request-json');

  exports.WidgetManager = (function() {
    function WidgetManager() {}

    WidgetManager.prototype.get = function(app, callback) {
      var client, path,
        _this = this;

      path = app.git.substring(19, app.git.length - 4);
      if (app.branch != null) {
        path = path + '/' + app.branch;
      } else {
        path = path + '/master';
      }
      client = request.newClient("https://raw.github.com/");
      return client.get(path + '/package.json', function(err, res, body) {
        if (err) {
          console.log(err);
          return callback(null, {});
        } else {
          if (res.statusCode !== 404) {
            if (body["cozy-widget"] != null) {
              _this.widget = body["cozy-widget"];
            } else {
              _this.widget = null;
            }
            console.log(_this.widget);
            return callback(null, _this.widget);
          } else {
            return callback(null, null);
          }
        }
      });
    };

    return WidgetManager;

  })();

}).call(this);
